# Tavily remote Web Search MCP (no local install needed)
[mcp_servers.tavily]
command = "cmd"
args = ["/c", "npx", "-y", "mcp-remote", "https://mcp.tavily.com/mcp/?tavilyApiKey=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"]
startup_timeout_ms = 120000   # give it plenty of time on first run

[mcp_servers.tavily.env]
SystemRoot = "C:\\Windows"

[mcp_servers.context7]
command = "cmd"
args = ["/c", "npx", "-y", "@upstash/context7-mcp"]
startup_timeout_ms = 30000

[mcp_servers.context7.env]
SystemRoot = "C:\\Windows"
